<a href="https://colab.research.google.com/github/pragya22/ML_Notebooks/blob/main/Intro_to_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
2+2

4

**Tensors**


*   A torch.Tensor is a multi-dimensional matrix containing elements of a single datatype.
*   Similar to Numpy arrays, but full of fun things that make them work better on GPUs(vs the regular CPUs).
*   More suitable for deep learning than a numpy array.
*   default datatype of float32(numpy is float64)
*   Just like python list.



**Python Lists**

In [2]:
my_list=[1,2,3,4]

In [4]:
my_list=[[1,2,3,4],[5,6,7,8]]
my_list

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [7]:
type(my_list)

list

**Numpy Arrays**

In [8]:
import numpy as np

In [11]:
np1=np.random.rand(3,4)
np1

array([[0.50365426, 0.9184525 , 0.88508889, 0.91212822],
       [0.56687601, 0.4707956 , 0.40444437, 0.37867224],
       [0.44667692, 0.53638616, 0.76327955, 0.76177744]])

In [10]:
np1.dtype

dtype('float64')

**Tensors**

In [13]:
import torch
tensor_2d=torch.randn(3,4)
tensor_2d

tensor([[-1.3676, -0.0868, -0.1005, -0.4735],
        [ 0.4366, -0.6158, -0.7326,  0.3156],
        [ 0.8462, -1.4034, -0.5373, -0.8301]])

In [15]:
torch_3d=torch.zeros(2,3,4)
torch_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [16]:
torch_3d.dtype

torch.float32

**convert numpy array to tensor**

In [18]:
my_tensor=torch.tensor(np1)
my_tensor

tensor([[0.5037, 0.9185, 0.8851, 0.9121],
        [0.5669, 0.4708, 0.4044, 0.3787],
        [0.4467, 0.5364, 0.7633, 0.7618]], dtype=torch.float64)

In [19]:
my_tensor.dtype

torch.float64

**TENSOR OPERATIONS**

SyntaxError: invalid syntax (<ipython-input-20-45926dc913d1>, line 1)