<a href="https://colab.research.google.com/github/pragya22/ML_Notebooks/blob/main/Intro_to_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
2+2

4

**Tensors**


*   A torch.Tensor is a multi-dimensional matrix containing elements of a single datatype.
*   Similar to Numpy arrays, but full of fun things that make them work better on GPUs(vs the regular CPUs).
*   More suitable for deep learning than a numpy array.
*   default datatype of float32(numpy is float64)
*   Just like python list.



**Python Lists**

In [ ]:
my_list=[1,2,3,4]

In [ ]:
my_list=[[1,2,3,4],[5,6,7,8]]
my_list

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [ ]:
type(my_list)

list

**Numpy Arrays**

In [ ]:
import numpy as np

In [ ]:
np1=np.random.rand(3,4)
np1

array([[0.50365426, 0.9184525 , 0.88508889, 0.91212822],
       [0.56687601, 0.4707956 , 0.40444437, 0.37867224],
       [0.44667692, 0.53638616, 0.76327955, 0.76177744]])

In [ ]:
np1.dtype

dtype('float64')

**Tensors**

In [ ]:
import torch
tensor_2d=torch.randn(3,4)
tensor_2d

tensor([[ 1.3101, -0.4736, -1.1127, -0.2369],
        [ 1.2919,  0.3878,  1.7760,  0.8863],
        [ 1.5111, -1.0383,  1.1823, -0.6086]])

In [ ]:
torch_3d=torch.zeros(2,3,4)
torch_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
torch_3d.dtype

torch.float32

**convert numpy array to tensor**

In [ ]:
my_tensor=torch.tensor(np1)
my_tensor

tensor([[0.5037, 0.9185, 0.8851, 0.9121],
        [0.5669, 0.4708, 0.4044, 0.3787],
        [0.4467, 0.5364, 0.7633, 0.7618]], dtype=torch.float64)

In [ ]:
my_tensor.dtype

torch.float64

**TENSOR OPERATIONS**

In [ ]:
my_torch=torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Reshape tensor : reshape and view**

In [ ]:
my_torch=my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch2=torch.arange(10)
my_torch2=my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch3=torch.arange(10)
my_torch3=my_torch2.reshape(-1,5)
my_torch3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch3=torch.arange(10)
my_torch4=my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

**Difference between reshape and view**

1.As the name suggests, torch.view merely creates a view of the original tensor. The new tensor will always share its data with the original tensor. This means that if you change the original tensor, the reshaped tensor will change and vice versa.

In [16]:
z=torch.zeros(3,2)
x=z.view(2,3)

In [17]:
x.fill_(1)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [18]:
z

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

2. To ensure that the new tensor always shares its data with the original, torch.view imposes some contiguity constraints on the shapes of the two tensors [docs]. More often than not this is not a concern, but sometimes torch.view throws an error even if the shapes of the two tensors are compatible. Here's a famous counter-example.

In [21]:
z=torch.zeros(3,2)
y=z.t()
print(y)
print(y.size())

tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.Size([2, 3])


In [25]:
y.view(6)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

3. torch.reshape doesn't impose any contiguity constraints, but also doesn't guarantee data sharing. The new tensor may be a view of the original tensor, or it may be a new tensor altogether.

In [32]:

z=torch.zeros(3,2)
print(z)
y=z.t()
print(y)
print(y.size())

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.Size([2, 3])


In [41]:
y.reshape(6)
print("reshape",y)
x=z.t().reshape(6)
print("x transpose reshape",x)
z.fill_(1)


reshape tensor([[1., 1., 1.],
        [1., 1., 1.]])
x transpose reshape tensor([1., 1., 1., 1., 1., 1.])


tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

If you just want to reshape tensors, use torch.reshape. If you're also concerned about memory usage and want to ensure that the two tensors share the same data, use torch.view.

In [36]:
z=torch.zeros(3,2)
z.reshape(6,1)

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])

**Slices**

In [47]:
my_torch7=torch.arange(10)
print(my_torch7)
print(my_torch7[7])
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor(7)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
my_torch8=[1,2,3,4,6]
torch.is_tensor(my_torch8)

False

In [52]:
my_torch8=torch.tensor(my_torch8)
torch.is_tensor(my_torch8)

True